const fs = require("node:fs");
const path = require("node:path");
const lunr = require("lunr");
const { minimatch } = require("minimatch");

/**
 * Based on code from https://github.com/cmfcmf/docusaurus-search-local/
 * by Christian Flach, licensed under the MIT license.
 */
function generateLunrClientJS(outDir, language = "en") {
  let normalizedLanguage = language;
  if (Array.isArray(normalizedLanguage) && normalizedLanguage.length === 1) {
    [normalizedLanguage] = normalizedLanguage;
  }
  let lunrClient =
    "// THIS FILE IS AUTOGENERATED\n" +
    "// DO NOT EDIT THIS FILE!\n\n" +
    'import * as lunr from "lunr";\n';

  if (normalizedLanguage !== "en") {
    require("lunr-languages/lunr.stemmer.support")(lunr);
    lunrClient += 'require("lunr-languages/lunr.stemmer.support")(lunr);\n';
    if (Array.isArray(normalizedLanguage)) {
      const languageCodes = normalizedLanguage.filter((code) => code !== "en");
      const needsTinySeg = languageCodes.some((code) => code === "ja" || code === "jp");

      if (needsTinySeg) {
        require("lunr-languages/tinyseg")(lunr);
        lunrClient += 'require("lunr-languages/tinyseg")(lunr);\n';
      }

      for (const code of languageCodes) {
        require(`lunr-languages/lunr.${code}`)(lunr);
        lunrClient += `require("lunr-languages/lunr.${code}")(lunr);\n`;
      }

      require("lunr-languages/lunr.multi")(lunr);
      lunrClient += `require("lunr-languages/lunr.multi")(lunr);\n`;
    } else {
      require(`lunr-languages/lunr.${normalizedLanguage}`)(lunr);
      lunrClient += `require("lunr-languages/lunr.${normalizedLanguage}")(lunr);\n`;
    }
  }
  lunrClient += `export default lunr;\n`;

  const lunrClientPath = path.join(outDir, "lunr.client.js");
  fs.writeFileSync(lunrClientPath, lunrClient);

  if (normalizedLanguage !== "en") {
    if (Array.isArray(normalizedLanguage)) {
      return lunr.multiLanguage(...normalizedLanguage);
    }
    return lunr[normalizedLanguage];
  }
  return null;
}

function getFilePaths(routesPaths, outDir, baseUrl, options = {}) {
  const files = [];
  const addedFiles = new Set();
  const { excludeRoutes = [], includeRoutes = [], indexBaseUrl = false } = options;
  const meta = {
    excludedCount: 0,
  };

  for (const route of routesPaths) {
    if (route === `${baseUrl}404.html`) continue;

    const isBaseUrl = route === baseUrl;

    if (isBaseUrl && !indexBaseUrl) continue;

    const relativePath = route.replace(baseUrl, "");
    const candidatePaths = [route, relativePath].flatMap((route) => {
      return [
        path.join(outDir, `${route}.html`),
        path.join(outDir, route, "index.html"),
      ];
    });

    const filePath = candidatePaths.find(fs.existsSync);
    if (!filePath) {
      // if this error occurs, likely docusaurus changed some file generation aspects
      // and we need to update the candidates above
      console.warn(
        `docusaurus-plugin-lunr: could not resolve file for route '${route}', it will be missing in the search index`,
      );
    }
    const resolvedFilePath = filePath ?? candidatePaths[0];

    // if we already added this file, skip it
    if (addedFiles.has(resolvedFilePath)) continue;

    // if we have include routes, skip if this route doesn't match any of them
    if (
      includeRoutes.length > 0 &&
      !includeRoutes.some(
        (includePattern) =>
          minimatch(route, includePattern) || minimatch(relativePath, includePattern),
      )
    ) {
      meta.excludedCount++;
      continue;
    }

    // if we have exclude routes, skip if this route matches any of them
    if (
      excludeRoutes.some(
        (excludePattern) =>
          minimatch(route, excludePattern) || minimatch(relativePath, excludePattern),
      )
    ) {
      meta.excludedCount++;
      continue;
    }

    files.push({ path: resolvedFilePath, url: route });
    addedFiles.add(resolvedFilePath);
  }
  return [files, meta];
}

module.exports = {
  generateLunrClientJS,
  getFilePaths,
};
